branches:
  only:
    - master
    - dev
    - AppVeyor
install:
  - set QTDIR=C:\Qt\5.10\mingw53_32
  - choco install -y InnoSetup
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;"C:\Program Files (x86)\Inno Setup 5"
build_script:
  - cd src
  - mkdir build
  - cd build
  - qmake ..\..\Hv2ray.pro
  - mingw32-make
