name: Qv2ray Push Build

on: push

jobs:
  Windows:
    name: Push build for win64
    runs-on: windows-2019
    steps:
      - name: Checking out Qv2ray sources
        uses: actions/checkout@master
      - name: Restoring submodules
        run: git submodule update --init
# --------------------------------------------------------
      - name: Installing Qt
        uses: jurplel/install-qt-action@v2
        with:
          arch: win64_mingw73
          modules: qtcharts
# --------------------------------------------------------
      - name: Extracting gRPC and protobuf libs and headers
        run: tools\grpc_gen.bat
# --------------------------------------------------------
      - name: Building Qv2ray
        shell: cmd
        run: |
          mkdir build
          cd build
          qmake .. CONFIG+=no_increase_build_number
          mingw32-make -j2
      - name: Copying DLLs to build output folders
        shell: cmd
        run: .github\workflows\copy_DLLs.bat
      - name: Make release zipball
        shell: cmd
        run: |
          cd build
          cd release
          del *.cpp *.h *.o *.qrc *.qm
          windeployqt ./qv2ray.exe --compiler-runtime
          cd ..
          ..\tools\7z.exe a Qv2ray.zip .\release
      - name: Uploading artifact
        uses: actions/upload-artifact@master
        with:
          name: Qv2ray.Win64.zip
          path: build/Qv2ray.zip

# =========================================================================================

  macOS:
    name: Push build for macOS
    runs-on: macOS-10.14
    steps:
      - name: Checking out sources
        uses: actions/checkout@master
      - name: Restoring submodules
        run: git submodule update --init
# --------------------------------------------------------
      - name: Installing Qt
        uses: jurplel/install-qt-action@v2
        with:
          modules: qtcharts
# --------------------------------------------------------
      - name: Extracting gRPC and protobuf libs and headers
        run: tools/deps_macOS.sh
# --------------------------------------------------------
      - name: Building Qv2ray
        run: |
          mkdir build
          cd build
          qmake .. CONFIG+=no_increase_build_number
          make -j2
      - name: Making release tarball
        run: |
          cd build
          cd qv2ray.app
          macdeployqt ./
          cd ..
          tar czf Qv2ray.app.tar.gz qv2ray.app
      - name: Uploading Artifact
        uses: actions/upload-artifact@master
        with:
          name: Qv2ray.macOS.app.zip
          path: build/Qv2ray.app.tar.gz
# ===================================================================================
          
  Linux:
    name: Push build for Linux
    runs-on: ubuntu-16.04
    steps:
      - name: Checking out sources
        uses: actions/checkout@master
      - name: Restoring submodules
        run: git submodule update --init
# --------------------------------------------------------
      - name: Installing Qt
        uses: jurplel/install-qt-action@v2
        with:
          modules: qtcharts
# --------------------------------------------------------
      - name: Install Packages 
        run: |
          sudo add-apt-repository ppa:webispy/grpc
          sudo add-apt-repository ppa:carsten-uppenbrink-net/openssl
          sudo apt update
          sudo apt install -y libgl-dev openssl libx11-dev libxkbcommon-x11-dev libgrpc++-dev libprotobuf-dev protobuf-compiler protobuf-c-compiler protobuf-compiler-grpc
# --------------------------------------------------------
      - name: Extracting gRPC and protobuf libs and headers
        run: tools/grpc_gen.sh
# --------------------------------------------------------
      - name: Generate Makefile
        run: |
          mkdir build
          cd build
          qmake .. CONFIG+=no_increase_build_number
      - name: Building Qv2ray
        run: |
          cd build
          make -j2
      - name: Generating filesystem structure for AppImage
        run: | 
          cd build
          make install INSTALL_ROOT=AppDir
          cd AppDir
          mkdir -p ./usr/lib/
          mkdir -p ./usr/bin/
          mv ./usr/local/bin/qv2ray ./usr/bin/qv2ray 
          cp /usr/lib/x86_64-linux-gnu/libssl.so.1.1 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 ./usr/lib/
      - name: Building AppImage using linuxdeployqt
        run: |
          cd build
          wget https://github.com/probonopd/linuxdeployqt/releases/download/6/linuxdeployqt-6-x86_64.AppImage
          chmod +x ./linuxdeployqt-6-x86_64.AppImage
          ./linuxdeployqt-6-x86_64.AppImage --appimage-extract 
          cd AppDir
          ../squashfs-root/AppRun usr/share/applications/qv2ray.desktop -appimage -no-strip -always-overwrite
          mv ./Qv2ray*.AppImage ./Qv2ray.AppImage
      - name: Uploading artifact
        uses: actions/upload-artifact@master
        with:
          name: Qv2ray.linux.AppImage
          path: build/AppDir/Qv2ray.AppImage

